### ISSUE TITLE
[BUG] Queue says -1 song playing when nothing is playing

### ISSUE THREAD

**Issue by TanapTheTimid** [Among-Suss/groov-in-c#18]
**Describe the bug**
Queue says -1 song playing when nothing is playing

**To Reproduce**
1. Play a song
2. Skip the song
3. Use Queue command

**Expected behavior**
It should say 0 songs in queue

**Comment by bexrr** [comment]
Hi, I'd like to fix this issue :)

**Comment by TanapTheTimid** [comment]
Hey, thanks for your interest in our project. If you're unfamiliar with the our project, try starting in src/discord-in-c/test2.c. show queue related code should be in show_queue_command()

**Comment by bexrr** [comment]
Do you think this should be fixed as well?
![queue_page_1_of_0](https://user-images.githubusercontent.com/72194279/135753602-4ad260ef-8021-4c28-bd37-f94f00e3f234.png)

(saying: Queue Page 1 of 0.)

**Comment by TanapTheTimid** [comment]
That would be great. There's another opened issue for that, but I'll go ahead and close it.

**Comment by TanapTheTimid** [comment]
Looks great, thanks! @poohcom1 this is ready to be merged.
