### ISSUE TITLE
[BUG] timestamp command on video with no timestamps

### ISSUE THREAD

**Issue by TanapTheTimid** [Among-Suss/groov-in-c#22]
**Describe the bug**
-timestamps command should say something like "No timestamps" when a song has no timestamps.

**To Reproduce**
1. Play a video with no timestamps in the description
2. -timestamps
3. bot message is just song title

**Expected behavior**
Something like "No timestamps"

**Comment by heckerfr0d** [comment]
Hello again :grin: 
Can I fix this too pleasee :innocent:
